[startup.ssh_init]
name = "bash"
running_delay = -1

[startup.ssh_init.args]
script = """
chmod 400 -R /etc/ssh/
mkdir -p /run/sshd
[ -d /root/.ssh/ ] || mkdir /root/.ssh
"""

[startup.sshd]
name = "core.system"
after = ["ssh_init"]
protected = true

[startup.sshd.args]
name = "/usr/sbin/sshd"
args = ["-e", "-D"]

[startup.postgres_init]
name = "bash"
after = ["sshd"]

[startup.postgres_init.args]
script = """
set -x
chown -R postgres.postgres /var/lib/postgresql/
chown -R postgres.postgres /var/log/postgresql
gpasswd -a postgres ssl-cert
chown root:ssl-cert  /etc/ssl/private/ssl-cert-snakeoil.key
chmod 640 /etc/ssl/private/ssl-cert-snakeoil.key
chown postgres:ssl-cert /etc/ssl/private
chown -R postgres /var/run/postgresql
chown -R postgres.postgres /etc/postgresql
find /var/lib/postgresql -maxdepth 0 -empty -exec sh -c 'pg_dropcluster 10 main && pg_createcluster 10 main' \\;
"""

[startup.setup]
name = "bash"
running_delay = -1
after = ["postgres_init"]

[startup.setup.args]
script = """
set -ex
echo 'remove a record was added by zos that make our server slow, below is resolv.conf file contents'
cat /etc/resolv.conf
sed -i '/^nameserver 10./d' /etc/resolv.conf
locale-gen en_US.UTF-8
export LC_ALL=en_US.UTF-8

# set threebot paramater from env varaibles
echo \"PRIVATE_KEY=$PRIVATE_KEY\" >> /etc/environment
echo \"THREEBOT_URL=$THREEBOT_URL\" >> /etc/environment
echo \"OPEN_KYC_URL=$OPEN_KYC_URL\" >> /etc/environment


# start postgres
service postgresql start

# taiga setup script
echo starting taiga setup script
wget https://raw.githubusercontent.com/threefoldtech/Threefold-Circles-Flist/master/setup_taiga.sh -O /.setup_taiga.sh
bash /.setup_taiga.sh

# add logs dir for taiga logs
[ -d  /home/taiga/logs ] || mkdir -p /home/taiga/logs
chown -R taiga:taiga /home/taiga

# taiga prepare script

chown -R root:root /usr/bin/sudo
chmod 4755 /usr/bin/sudo
echo  starting taiga prepare script
prepare_taiga_file='/.prepare_taiga.sh'
wget https://raw.githubusercontent.com/threefoldtech/Threefold-Circles-Flist/master/prepare_taiga.sh -O ${prepare_taiga_file}
sudo chmod +x /.prepare_taiga.sh
su taiga -c 'bash /.prepare_taiga.sh'

sed -i \"s/listen 80 default_server/listen $HTTP_PORT default_server/g\" /etc/nginx/conf.d/taiga.conf
sudo nginx -t

# Start rabbitmq-server and create user+vhost
chown -R rabbitmq:rabbitmq /etc/rabbitmq
chown -R rabbitmq:rabbitmq /var/lib/rabbitmq/
chown -R rabbitmq:rabbitmq /var/log/rabbitmq/
service rabbitmq-server start
rabbitmqctl add_user taiga $SECRET_KEY
rabbitmqctl add_vhost taiga
rabbitmqctl set_permissions -p taiga taiga '.*' '.*' '.*'

service nginx start

"""

[startup.taigaBack]
name = "bash"
after = ["setup"]
protected = true

[startup.taigaBack.args]
script = """
set -x
su taiga -c 'cd /home/taiga/taiga-back ; /home/taiga/taiga-back/taiga/bin/gunicorn --workers 4 --timeout 60 -b 127.0.0.1:8001 taiga.wsgi'
"""

[startup.taigaEvents]
name = "bash"
after = ["setup"]
protected = true

[startup.taigaEvents.args]

script = """
set -x
su taiga -c 'cd /home/taiga/taiga-events ; /home/taiga/taiga-events/node_modules/coffeescript/bin/coffee /home/taiga/taiga-events/index.coffee'
"""

[startup.s3Backup]
name = "bash"
after = ["setup"]
recurring_period=7200

[startup.s3Backup.args]
script = """
set -x
bkp_directory='/home/taiga/taiga-backup'
media_directory='/home/taiga/taiga-back/media'
[ -d $bkp_directory ] || ( mkdir $bkp_directory && chown -R taiga:taiga $bkp_directory )
[ -d $media_directory ] || ( mkdir $media_directory && chown -R taiga:taiga $media_directory )

date=`date +%d%m%y%H%M`

#Database backup
su - taiga -c \"pg_dump -U taiga -c taiga > $bkp_directory/db-bkp-$date-dump.sql\"

#File system backup
zip -r $bkp_directory/app-bkp-$date.zip $media_directory >> /dev/null 3>&1

unset HISTFILE
if ! restic snapshots ;then echo restic repo does not initalized yet; restic init ; fi > /dev/null
restic backup --cleanup-cache /home/taiga/taiga-backup
restic forget -q --prune --keep-within 1m

#Delete files older than 3 days
find $bkp_directory/ -mtime +3 -delete

"""
